spring.datasource.url=jdbc:mysql://localhost:3306/camposflow_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:enginner}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true